<?php
/**
 * Created by PhpStorm.
 * User: vench
 * Date: 18.12.18
 * Time: 22:08
 */

namespace app\modules\activity\models;


trait SetDefaultDateTrait
{


    public function beforeValidate()
    {

        if(empty($this->activity_end_timestamp)) {
            $this->activity_end_timestamp = $this->activity_start_timestamp;
        }

        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }
}